version: "3"

services:
  app:
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MONGO_URL: "mongodb://db:27017"
      NODE_ENV: "production"
    depends_on:
      - "db"
  db:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
